<?php $settings = array(
  'site_url' => 'https://' . $_SERVER['HTTP_HOST'].'/a',
  'projectsecurity_path' => 'https://' . $_SERVER['HTTP_HOST'] . '/a/h4ci',
  'username' => 'login@h4ci',
  'password' => 'a1b2299b8272a202c5012c24b4ea60c80d93a402d98ec765d58718c9c8d5453e', //asdHaciAk!23
  'email' => 'admin@mail.com',
  'project_security' => 1,
  'mail_notifications' => 0,
  'test_integration' => 0,
  'dark_mode' => 1,
  'countryban_blacklist' => 1,
  'live_traffic' => 1,
  'badword_replace' => '[Censored]',
  'error_reporting' => '5',
  'display_errors' => '1',
  'sqli_protection2' => 1,
  'sqli_protection3' => 0,
  'sqli_protection4' => 1,
  'sqli_protection5' => 1,
  'sqli_protection6' => 1,
  'sqli_protection7' => 1,
  'sqli_protection8' => 1,
  'sqli_protection' => 1,
  'sqli_logging' => 1,
  'sqli_autoban' => 1,
  'sqli_redirect' => 'https://www.youtube.com/watch?v=8ilDyjevQDw',
  'sqli_mail' => 0,
  'badbot_protection' => 1,
  'badbot_protection2' => 1,
  'badbot_protection3' => 1,
  'badbot_logging' => 1,
  'badbot_autoban' => 1,
  'badbot_mail' => 0,
  'proxy_protection2' => 0,
  'proxy_protection' => 0,
  'proxy_api1' => '',
  'proxy_api2' => '',
  'proxy_api3' => '',
  'proxy_logging' => 1,
  'proxy_mail' => 0,
  'proxy_redirect' => 'https://www.youtube.com/watch?v=8ilDyjevQDw',
  'spam_protection' => 0,
  'spam_logging' => 1,
  'spam_redirect' => 'https://www.youtube.com/watch?v=8ilDyjevQDw',
  'spam_mail' => 0,
);
